### ISSUE TITLE
Creation of device manually : display enum from a binding list into device configuration

### ISSUE THREAD

**Issue by jmberhault** [Yadoms/yadoms#243] opened 2017-05-03 11:58 UTC
When editing  the configuration a device created manually, the display of a binding parameter looks not work properly : 

![image](https://cloud.githubusercontent.com/assets/16737541/25659493/548c0594-3008-11e7-9ef9-3acf409ebc58.png)

Try with create the IPX800 plugin -> create a device manually. Create any device. Edit this device configuration.

**Comment by jano42** [comment] 2017-05-05 11:49
Not a bug. This is due to bad plugin asnwer of binding request.

Fixed in branch 2_0_0

**Closed by jano42** 2017-05-05 11:49 UTC
Labels: Bug/Major
