### ISSUE TITLE
[Blockly] Functions doesn't work

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#374] opened 2017-11-28 10:17 UTC
This rule can not be validated : 
![image](https://user-images.githubusercontent.com/6855339/33314213-3fbe48c4-d42d-11e7-9cc7-35c7f0ca9836.png)

Error in console : 
![image](https://user-images.githubusercontent.com/6855339/33314311-875852b0-d42d-11e7-97d6-81611e335440.png)

**Comment by jano42** [comment] 2017-11-28 10:35
Can't reproduce


![image](https://user-images.githubusercontent.com/3135683/33315089-f109a9e6-d42f-11e7-8fbb-165cdd671950.png)


![image](https://user-images.githubusercontent.com/3135683/33315149-210bfb9e-d430-11e7-8a6d-b1aa2c1b1015.png)

Please check if version is from branch 2_0_0 !

**Comment by sgallou** [comment] 2017-11-28 10:42
Please use a function block...

**Comment by jano42** [comment] 2017-11-29 14:19
Fixed in branch 2_0_0

**Closed by jano42** 2017-11-29 14:19 UTC
Labels: Bug/Major
