### ISSUE TITLE
ZWave does not wake up after reboot.

### ISSUE THREAD

**Issue by klorydryk** [Yadoms/yadoms#267] opened 2017-06-05 20:08 UTC
After being asked to reboot my raspberry for #253 , I can't get ZWave working.
I re-installed rc4 from sources, and ZWave plugin is working from fresh installation, but then I stop Yasdom, copy yasdom.db3 and scripts from my previous installation, restart yasdom.. and it is not working, in ttyUSB0 (controller ready -> started -> error) or in ttyAMA0 (stopped).

My dmesg for tty:
```
[    0.000000] Kernel command line: bcm2708_fb.fbwidth=656 bcm2708_fb.fbheight=416 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x1ec00000 vc_mem.mem_size=0x20000000  dwc_otg.lpm_enable=0 console=ttyAMA0,115200 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait
[    0.001389] console [tty1] enabled
[    1.057854] 20201000.serial: ttyAMA0 at MMIO 0x20201000 (irq = 81, base_baud = 0) is a PL011 rev2
[    1.894862] console [ttyAMA0] enabled
[    3.791327] systemd[1]: Expecting device dev-ttyAMA0.device...
[    7.981714] usb 1-1.3: cp210x converter now attached to ttyUSB0
```

**Comment by jano42** [comment] 2017-06-07 06:26
OK I think I know what happens.

There is also a "data" folder next to plugin executable. If it is not restored, it could fail.

I suggest you to delete the plugin instance, and recreate it.
Then just update your scripts/rule to adjust device/keywords selections.

**Comment by klorydryk** [comment] 2017-06-07 07:56
Already tried. And I got an error.
-> I needed to delete the ZWave/data folder to make it work. At last. A few days without light for my fishes :s

**Comment by klorydryk** [comment] 2017-06-07 21:54
I have 2 ZWave FGWPE Wall Plug equipment, listed and receiving data. But the Switch widget only offer "system". What is exactly the problem? It was working before this reboot -_-

**Comment by jano42** [comment] 2017-06-08 04:36
Could you send me the plugin data folder and your database file ?

**Comment by klorydryk** [comment] 2017-06-08 07:53
here it is: https://quaidu13.fr:5001/sharing/mivlQRDKx

**Comment by jano42** [comment] 2017-06-12 12:12
Thanks for files ;-)
I've seen a potential problem.

Could you please send me logs and zwave data:

Yadoms install path
- logs (<- this folder)
- plugins
    - ZWave
        - data  (<- this folder)

**Comment by klorydryk** [comment] 2017-06-15 15:52
here it is!
https://quaidu13.fr:5001/sharing/gV1URLAEg
(for information, ZWave stopped yeterday for no reason, and refuses to restart).

**Comment by jmberhault** [comment] 2017-09-06 19:21
This arrive to me this evening in branch 2_0_0. The dongle disappear from windows, et doesn't reappear.

**Comment by jano42** [comment] 2017-10-10 09:34
Close this issue because don't reproductible or not a bug.

Tested:

- start the plugin without "data" folder (contains the zwave network configuration) => the folder and files are created

- I disconnect the dongle then start the plugin (may also simulate a serial port change after a reboot) => the plugin fail to start, and is displayed "stop". The log file match comment @jmberhault https://github.com/Yadoms/yadoms/issues/267#issuecomment-327587160 . This is a correct behavior. If the dongle is not present => the plugin win't start.

The only thing to do to enhance it, is to add a clear message to user. (=> #323)

**Closed by jano42** 2017-10-10 09:34 UTC
Labels: Bug/Major, ZWave
